name: app
description: Una nueva aplicación Flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.3.0
  shared_preferences: ^2.2.0
  url_launcher: ^6.2.5
  webview_flutter: ^4.2.2
  flutter_map: ^6.1.0
  geolocator: ^11.0.0
  latlong2: ^0.9.0
  font_awesome_flutter: ^10.6.0
  google_fonts: ^4.0.3
  animate_do: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  integration_test:
    sdk: flutter
  junitreport: ^2.0.2  # ✅ Esto va aquí, fuera de integration_test


flutter:
  uses-material-design: true

  assets:
    - assets/images/
